### ISSUE TITLE
Execute PUMA in python script as a package

### ISSUE THREAD

**Issue by MengXiangxi** [ENHANCE-PET/PUMA#23]
Hi! I am wondering if it is possible to execute PUMA as a python package using the `import` command, just like in MOOSE:

```python
frome moosez import moose
```

I looked up the `pumaz.py` code but failed to locate a similar function. I am wondering if it is possible to add one? It will help to streamline the workflow I am building. Thank you!

**Comment by Keyn34** [comment]
Hi @MengXiangxi, 

Currently, puma is not equipped with such a function, but we can make one. I can take a look at it this week.
